INSERT INTO events (
    title,
    description,
    organizer_id,
    status,
    category,
    price,
    currency,
    location,
    start_date,
    end_date,
    ticket_mode,
    capacity,
    average_rating,
    total_reviews,
    refundable,
    refund_deadline_days,
    refund_policy,
    created_at,
    updated_at,
    published_at
)
VALUES (
           'Village Food Festival',
           'Traditional rural food event.',
           2,
           'APPROVED',
           'FOOD',
           5.00,
           'EUR',
           'Bragança',
           '2026-06-15',
           '2026-06-17',
           'PER_DAY',
           240,
           4,
           3,
           true,
           7,
           'Refunds are available up to 7 days before the event starts.',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       ),
       (
           'Tree Festival',
           'To celebrate the beauty of trees.',
           2,
           'APPROVED',
           'NATURE',
           15.00,
           'EUR',
           'Leiria',
           '2026-06-25',
           '2026-06-27',
           'EVENT_PASS',
           200,
           0,
           0,
           true,
           1,
           'Refunds are available up to 1 day before the event starts.',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       ),
       (
           'Pottery Event',
           'To celebrate the beauty of pottery.',
           2,
           'APPROVED',
           'WORKSHOP',
           19.99,
           'EUR',
           'Algarve',
           '2026-06-28',
           '2026-06-28',
           'EVENT_PASS',
           34,
           0,
           0,
           true,
           1,
           'Refunds are available up to 1 day before the event starts.',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       ),
       (
           'Portuguese Agriculture Fair',
           'To celebrate the beauty of Portuguese agriculture.',
           2,
           'APPROVED',
           'TRADITION',
           0,
           'EUR',
           'Ribatejo',
           '2026-06-29',
           '2026-06-29',
           'EVENT_PASS',
           9000,
           0,
           0,
           false,
           0,
           '',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       ),
       (
           'Wood Carving Workshop',
           'To celebrate the beauty of wood carving.',
           2,
           'APPROVED',
           'WORKSHOP',
           10,
           'EUR',
           'Coimbra',
           '2026-06-21',
           '2026-06-21',
           'EVENT_PASS',
           50,
           0,
           0,
           false,
           0,
           '',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       ),
       (
           'Horse care and riding workshop',
           'This event focuses on teaching participants about horse care techniques by professionals, so they can learn proper care and riding skills.',
           2,
           'APPROVED',
           'WORKSHOP',
           55,
           'EUR',
           'Setúbal',
           '2026-06-28',
           '2026-06-28',
           'EVENT_PASS',
           50,
           0,
           0,
           false,
           0,
           '',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       );

INSERT INTO event_images (event_id, image_url)
VALUES
    (1, 'https://sustainablefoodtrust.org/wp-content/uploads/2023/05/Copy-of-New-website-image-size-34.jpg'),
    (1, 'https://amuse-bouche.pt/wp-content/uploads/2021/04/Lisboafood_.jpg'),
    (1, 'https://blog.italotreno.com/wp-content/uploads/2025/05/summer-food-festivals-italy.jpg'),
    (2, 'https://f4v2a8t7.delivery.rocketcdn.me/wp-content/uploads/2018/09/Into-The-Trees_2-1440x938.jpg'),
    (2, 'https://static.wixstatic.com/media/4b74f6_269c733445f14a1aad02dc6e7394f8ac~mv2.jpg/v1/fill/w_714,h_402,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/4b74f6_269c733445f14a1aad02dc6e7394f8ac~mv2.jpg'),
    (3, 'https://algarveimaterial.wordpress.com/wp-content/uploads/2017/01/olaria.jpg'),
    (3, 'https://www.cm-lagoa.pt/cmlagoaalgarve/uploads/poi/image/39/olaria.jpg'),
    (4, 'https://www.entroncamentoonline.pt/portal/wp-content/uploads/2021/06/FNA-21.jpg'),
    (4, 'https://agriculturaemar.com/wp-content/uploads/2025/05/FNA-25-%E2%80%93-Feira-Nacional-de-Agricultura-493052804_1091663386337614_3965933546973740750_n.jpg'),
    (5, 'https://www.historicbethlehem.org/app/uploads/2025/06/Whittling-stock-image.jpg'),
    (5, 'https://www.thegoodlifecentre.co.uk/wp-content/uploads/2021/08/Woodcarving.jpg'),
    (6, 'https://www.oysterworldwide.com/panel/wp-content/uploads/2021/05/Prj_Portugal_horse_care.jpg'),
    (6, 'https://staglodgestables.com/wp-content/uploads/2020/01/Pony-Club-900x600-new.jpg');

INSERT INTO event_daily_capacities (event_id, date, capacity)
VALUES
    (1, '2026-06-15', 80),
    (1, '2026-06-16', 100),
    (1, '2026-06-17', 60);