spring.application.name=CloudGateway
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Use Gateway MVC, not WebFlux
spring.cloud.gateway.server.webflux.enabled=false
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=false

# Static route to user-service
spring.cloud.gateway.server.webmvc.routes[0].id=rota-user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**,/internal/users/**
spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Method=GET,POST,PUT,DELETE


spring.cloud.gateway.server.webmvc.routes[1].id=rota-auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webmvc.routes[1].predicates[1]=Method=GET,POST,PUT,DELETE


# Static route to event-service
spring.cloud.gateway.server.webmvc.routes[2].id=rota-event-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/events/**,/internal/events/**,/uploads/**
spring.cloud.gateway.server.webmvc.routes[2].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH

# Static route to review-service
spring.cloud.gateway.server.webmvc.routes[3].id=rota-review-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/reviews/**
spring.cloud.gateway.server.webmvc.routes[3].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH


# Static route to ticket-service
spring.cloud.gateway.server.webmvc.routes[4].id=rota-ticket-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/tickets/**,/internal/tickets/**
spring.cloud.gateway.server.webmvc.routes[4].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH

# Static route to payment-service
spring.cloud.gateway.server.webmvc.routes[5].id=rota-payment-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/payment/**
spring.cloud.gateway.server.webmvc.routes[5].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH

# Static route to notification-service
spring.cloud.gateway.server.webmvc.routes[6].id=rota-notification-service
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/notification/**,/internal/notifications/**,/debug/**
spring.cloud.gateway.server.webmvc.routes[6].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH

# Static route to content-service
spring.cloud.gateway.server.webmvc.routes[7].id=rota-content-service
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/content/**
spring.cloud.gateway.server.webmvc.routes[7].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH

# Helpful debug logs
logging.level.org.springframework.cloud.gateway=DEBUG

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB