spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: API Gateway
    description: Gateway for Best Rural Events
    version: 0.0.1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka