spring.application.name=CloudGateway
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Use Gateway MVC, not WebFlux
spring.cloud.gateway.server.webflux.enabled=false
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=false

# Static route to user-service
spring.cloud.gateway.server.webmvc.routes[0].id=rota-user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**,/internal/users/**
spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Method=GET,POST,PUT,DELETE


spring.cloud.gateway.server.webmvc.routes[1].id=rota-auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webmvc.routes[1].predicates[1]=Method=GET,POST,PUT,DELETE


# Static route to event-service
spring.cloud.gateway.server.webmvc.routes[2].id=rota-event-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/events/**,/internal/events/**
spring.cloud.gateway.server.webmvc.routes[2].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH

# Helpful debug logs
logging.level.org.springframework.cloud.gateway=DEBUG