spring.application.name=AuthService
server.port=8082

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

services.user-service.url=http://localhost:8080

jwt.secret=CHANGE_THIS_SECRET_TO_A_LONG_RANDOM_STRING_32_CHARS_MINIMUM
jwt.expiration-minutes=120

management.endpoints.web.exposure.include=health,info


logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
