insert into auth_users (
    email,
    password_hash,
    role,
    enabled,
    created_at,
    updated_at
)
values
    (
        'a@a.a',
        '$2a$10$qEANp32uC9gOA78otGrnX.wcoyU.FqeYrZAGbI702AqXYBeVr.vYy',
        'USER',
        true,
        current_timestamp,
        current_timestamp
    ),
    (
        'maria3@example.com',
        '$2a$10$qEANp32uC9gOA78otGrnX.wcoyU.FqeYrZAGbI702AqXYBeVr.vYy',
        'USER',
        true,
        current_timestamp,
        current_timestamp
    ),
    (
        'admin@a.a',
        '$2a$10$qEANp32uC9gOA78otGrnX.wcoyU.FqeYrZAGbI702AqXYBeVr.vYy',
        'ADMIN',
        true,
        current_timestamp,
        current_timestamp
    );